spring:
  datasource:
    username: root
    password: 5517
    url: jdbc:mysql://localhost:3306/spring_cache
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.0.107
#控制台打印sql
logging:
  level:
    com:
      example:
        springboot_cache:
                    mapper: debug
#下划线转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
